// Auto-generated by Gemini CLI — Last updated: 2026-05-16
import { type OpenApiSpec } from "@scalar/express-api-reference"

export const openAPISpec = {
  openapi: "3.0.3",
  info: {
    title: "VOLETRA API",
    description: "API Documentation for VOLETRA (Volunteer Tracking and Management) Platform. This API handles user authentication, mission management (CRUD + Geocoding), and volunteer applications with race-condition safety.",
    version: "1.0.0",
    contact: {
      name: "VOLETRA Team",
      url: "https://voletra.id",
    },
  },
  servers: [
    {
      url: "http://localhost:3000",
      description: "Development Server",
    },
  ],
  tags: [
    { name: "Auth", description: "Authentication and Authorization" },
    { name: "Misi", description: "Mission Management" },
    { name: "Apply", description: "Volunteer Application Management" },
    { name: "User", description: "User Profile Management" },
    { name: "Edukasi", description: "Educational Resources" },
    { name: "Admin", description: "Administrator Control Panel" },
  ],
  components: {
    securitySchemes: {
      cookieAuth: {
        type: "apiKey",
        in: "cookie",
        name: "access_token",
        description: "JWT session token stored in an HttpOnly cookie.",
      },
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "JWT",
        description: "JWT token for testing in Postman or other CLI tools.",
      },
    },
    schemas: {
      Error: {
        type: "object",
        properties: {
          success: { type: "boolean", example: false },
          message: { type: "string", example: "Error message details" },
          error: { type: "string", example: "ERROR_CODE" },
        },
      },
      ValidationError: {
        type: "object",
        properties: {
          success: { type: "boolean", example: false },
          message: { type: "string", example: "Validasi gagal" },
          errors: {
            type: "object",
            additionalProperties: {
              type: "array",
              items: { type: "string" },
            },
          },
        },
      },
      User: {
        type: "object",
        properties: {
          user_id: { type: "string", format: "uuid" },
          name: { type: "string" },
          email: { type: "string", format: "email" },
          role: { type: "string", enum: ["volunteer", "lembaga", "super_admin"] },
        },
      },
      Mission: {
        type: "object",
        properties: {
          id: { type: "string", format: "uuid" },
          judul: { type: "string" },
          deskripsi: { type: "string" },
          kategori: { type: "string", enum: ["Pendidikan", "Bencana", "Medis", "Logistik"] },
          alamat: { type: "string" },
          latitude: { type: "number" },
          longitude: { type: "number" },
          jumlah_relawan: { type: "integer", description: "Kuota total relawan yang dibutuhkan" },
          volunteers_applied: { type: "integer", description: "Jumlah relawan yang sudah terdaftar" },
          status: { type: "string", enum: ["Open", "Full", "In Progress", "Completed"] },
          foto: { type: "array", items: { type: "string", format: "uri" } },
          coordinator_whatsapp: { type: "string", description: "Hanya muncul jika approved" },
        },
      },
    },
  },
  paths: {
    "/api/auth/register/volunteer": {
      post: {
        tags: ["Auth"],
        summary: "Register as a Volunteer",
        description: "Creates a new volunteer account. Password requires 1 uppercase letter and 1 number.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["name", "email", "password", "confirm_password", "role"],
                properties: {
                  name: { type: "string", example: "Budi Santoso" },
                  email: { type: "string", format: "email", example: "budi.santoso@email.com" },
                  password: { type: "string", format: "password", example: "Password123" },
                  confirm_password: { type: "string", format: "password", example: "Password123" },
                  role: { type: "string", enum: ["volunteer"], example: "volunteer" },
                },
              },
            },
          },
        },
        responses: {
          201: {
            description: "Registrasi berhasil",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    success: { type: "boolean", example: true },
                    message: { type: "string", example: "Registrasi berhasil!" },
                    data: {
                      type: "object",
                      properties: {
                        user_id: { type: "string", format: "uuid" },
                        name: { type: "string" },
                        email: { type: "string" },
                        role: { type: "string" },
                        redirect_url: { type: "string" },
                      },
                    },
                  },
                },
              },
            },
          },
          400: { $ref: "#/components/responses/ValidationError" },
          409: { description: "Email sudah terdaftar" },
        },
      },
    },
    "/api/auth/register/lembaga": {
      post: {
        tags: ["Auth"],
        summary: "Register as an Institution (Lembaga)",
        description: "Creates a new institution account for reporting missions.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["institution_name", "email", "password", "confirm_password", "role"],
                properties: {
                  institution_name: { type: "string", example: "Yayasan Kasih Ibu" },
                  email: { type: "string", format: "email", example: "contact@kasihibu.org" },
                  password: { type: "string", format: "password", example: "Lembaga2024" },
                  confirm_password: { type: "string", format: "password", example: "Lembaga2024" },
                  role: { type: "string", enum: ["lembaga"], example: "lembaga" },
                },
              },
            },
          },
        },
        responses: {
          201: {
            description: "Registrasi berhasil",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    success: { type: "boolean", example: true },
                    message: { type: "string", example: "Registrasi institusi berhasil!" },
                    data: {
                      type: "object",
                      properties: {
                        user_id: { type: "string", format: "uuid" },
                        name: { type: "string" },
                        email: { type: "string" },
                        role: { type: "string" },
                        redirect_url: { type: "string" },
                      },
                    },
                  },
                },
              },
            },
          },
          400: { $ref: "#/components/responses/ValidationError" },
          409: { description: "Email sudah terdaftar" },
        },
      },
    },
    "/api/auth/login": {
      post: {
        tags: ["Auth"],
        summary: "Login",
        description: "Standard email/password login. Includes rate limiting: 5 attempts per 10 mins.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["email", "password"],
                properties: {
                  email: { type: "string", format: "email", example: "budi.santoso@email.com" },
                  password: { type: "string", format: "password", example: "Password123" },
                },
              },
            },
          },
        },
        responses: {
          200: {
            description: "Login berhasil",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    success: { type: "boolean", example: true },
                    message: { type: "string", example: "Login berhasil!" },
                    data: {
                      type: "object",
                      properties: {
                        role: { type: "string" },
                        redirect_url: { type: "string" },
                      },
                    },
                  },
                },
              },
            },
          },
          401: { description: "Email atau kata sandi salah" },
          403: { description: "Akun dinonaktifkan" },
          429: { description: "Terlalu banyak percobaan (Rate limited)" },
        },
      },
    },
    "/api/auth/logout": {
      post: {
        tags: ["Auth"],
        summary: "Logout",
        description: "Clears the HttpOnly access_token cookie.",
        responses: {
          200: { description: "Logout berhasil" },
        },
      },
    },
    "/api/auth/google": {
      post: {
        tags: ["Auth"],
        summary: "Google OAuth Login/Register",
        description: "Authenticates using Google ID Token. New users are automatically registered as volunteers.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["id_token"],
                properties: {
                  id_token: { type: "string", example: "eyJhbGciOiJSUzI1NiIs..." },
                },
              },
            },
          },
        },
        responses: {
          200: { description: "Login berhasil" },
          201: { description: "Akun baru berhasil dibuat via Google" },
          400: { description: "Token tidak valid" },
          409: { description: "Email terdaftar sebagai institusi" },
        },
      },
    },
    "/api/auth/forgot-password": {
      post: {
        tags: ["Auth"],
        summary: "Forgot Password",
        description: "Sends a reset link to the user's email if it exists. Note: Always returns success to prevent email enumeration.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["email"],
                properties: {
                  email: { type: "string", format: "email", example: "budi.santoso@email.com" },
                },
              },
            },
          },
        },
        responses: {
          200: { description: "Email reset sent (if exists)" },
        },
      },
    },
    "/api/auth/reset-password": {
      post: {
        tags: ["Auth"],
        summary: "Reset Password",
        description: "Resets password using a valid token from the reset link.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["token", "new_password"],
                properties: {
                  token: { type: "string", example: "7f8e... (32 chars hex)" },
                  new_password: { type: "string", format: "password", example: "NewPassword123" },
                },
              },
            },
          },
        },
        responses: {
          200: { description: "Password berhasil direset" },
          410: { description: "Token kedaluwarsa atau tidak valid" },
        },
      },
    },
    "/api/misi": {
      get: {
        tags: ["Misi"],
        summary: "Get All Missions",
        description: "Retrieve a list of public missions. Can filter by location (radius) and category. Only shows Open, In Progress, and Full statuses.",
        parameters: [
          { name: "lat", in: "query", schema: { type: "number" }, example: -6.1751 },
          { name: "lng", in: "query", schema: { type: "number" }, example: 106.8272 },
          { name: "radius", in: "query", schema: { type: "number" }, description: "Radius in kilometers", example: 10 },
          { name: "kategori", in: "query", schema: { type: "string", enum: ["Bencana", "Pendidikan", "Medis", "Logistik"] }, example: "Bencana" },
        ],
        responses: {
          200: {
            description: "Success",
            content: {
              "application/json": {
                schema: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      id: { type: "string", format: "uuid" },
                      judul: { type: "string" },
                      kategori: { type: "string" },
                      latitude: { type: "number" },
                      longitude: { type: "number" },
                      status: { type: "string" },
                      jumlah_relawan: { type: "integer" },
                    },
                  },
                },
              },
            },
          },
        },
      },
      post: {
        tags: ["Misi"],
        summary: "Create New Mission",
        description: "Creates a new mission. Automatic geocoding of the address via OpenStreetMap. Only for Lembaga.",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        requestBody: {
          required: true,
          content: {
            "multipart/form-data": {
              schema: {
                type: "object",
                required: ["judul", "deskripsi", "kategori", "alamat", "jumlah_relawan"],
                properties: {
                  judul: { type: "string", example: "Bantuan Banjir Jakarta" },
                  deskripsi: { type: "string", example: "Membantu evakuasi dan pembagian logistik di wilayah Kemang." },
                  kategori: { type: "string", enum: ["Bencana", "Pendidikan", "Medis", "Logistik"], example: "Bencana" },
                  alamat: { type: "string", example: "Jl. Kemang Raya No. 1, Jakarta Selatan" },
                  jumlah_relawan: { type: "integer", example: 20 },
                  foto: { type: "array", items: { type: "string", format: "binary" } },
                },
              },
            },
          },
        },
        responses: {
          201: {
            description: "Created",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    id: { type: "string", format: "uuid" },
                    message: { type: "string" },
                  },
                },
              },
            },
          },
          400: { description: "Lokasi tidak valid atau validasi gagal" },
        },
      },
    },
    "/api/misi/pelapor/me": {
      get: {
        tags: ["Misi"],
        summary: "Get My Reported Missions",
        description: "Returns a list of all missions created by the authenticated institution. Includes full mission details with mapped category and status strings.",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        responses: {
          200: {
            description: "Success",
            content: {
              "application/json": {
                schema: {
                  type: "array",
                  items: { $ref: "#/components/schemas/Mission" },
                },
                example: [
                  {
                    id: "67e5f4af-3f88-449a-bc2b-83b7996f63c8",
                    lembagaId: "u1v2w3x4...",
                    title: "Bantuan Pangan Korban Banjir",
                    description: "Distribusi paket sembako untuk warga terdampak banjir di bantaran sungai.",
                    category: "Bencana",
                    address: "Jl. Braga No. 12, Bandung",
                    latitude: -6.9175,
                    longitude: 107.6191,
                    volunteersNeeded: 15,
                    volunteersApplied: 5,
                    coordinator_whatsapp: "081234567890",
                    status: "Open",
                    photos: ["https://res.cloudinary.com/.../img1.jpg"],
                    createdAt: "2026-05-10T08:00:00.000Z",
                    updatedAt: "2026-05-15T10:30:00.000Z"
                  }
                ]
              },
            },
          },
          401: { description: "Akses ditolak. Silakan login terlebih dahulu." },
          403: { description: "Hanya untuk peran Lembaga." },
        },
      },
    },
    "/api/misi/{id}": {
      get: {
        tags: ["Misi"],
        summary: "Get Mission Detail",
        description: "Retrieve full details of a specific mission. coordinator_whatsapp is hidden unless the user is an approved volunteer.",
        parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }],
        responses: {
          200: {
            description: "Success",
            content: { "application/json": { schema: { $ref: "#/components/schemas/Mission" } } },
          },
          404: { description: "Misi tidak ditemukan" },
        },
      },
      put: {
        tags: ["Misi"],
        summary: "Update Mission",
        description: "Update mission details. Address change triggers re-geocoding. Only for Lembaga (Owner).",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }],
        requestBody: {
          content: {
            "multipart/form-data": {
              schema: {
                type: "object",
                properties: {
                  judul: { type: "string" },
                  deskripsi: { type: "string" },
                  kategori: { type: "string", enum: ["Bencana", "Pendidikan", "Medis", "Logistik"] },
                  alamat: { type: "string" },
                  jumlah_relawan: { type: "integer" },
                  foto: { type: "array", items: { type: "string", format: "binary" } },
                },
              },
            },
          },
        },
        responses: {
          200: { description: "Berhasil diperbarui" },
          404: { description: "Misi tidak ditemukan" },
        },
      },
      delete: {
        tags: ["Misi"],
        summary: "Soft Delete Mission",
        description: "Marks a mission as deleted. It will no longer appear in public searches.",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }],
        responses: {
          200: { description: "Misi berhasil dihapus" },
        },
      },
    },
    "/api/misi/{id}/status": {
      patch: {
        tags: ["Misi"],
        summary: "Update Mission Status",
        description: "Manually advance mission status. Transition: Full -> In Progress -> Completed.",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }],
        requestBody: {
          required: true,
          content: {
            "application/x-www-form-urlencoded": {
              schema: {
                type: "object",
                required: ["status"],
                properties: {
                  status: { type: "string", enum: ["berjalan", "selesai"], example: "berjalan" },
                },
              },
            },
          },
        },
        responses: {
          200: { description: "Status updated" },
          400: { description: "Transisi tidak valid" },
        },
      },
    },
    "/api/misi/{id}/applicants": {
      get: {
        tags: ["Misi"],
        summary: "Get Mission Applicants",
        description: "List all volunteers who applied to this mission. Only for the mission owner.",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }],
        responses: {
          200: {
            description: "Success",
            content: {
              "application/json": {
                schema: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      apply_id: { type: "string", format: "uuid" },
                      user_id: { type: "string", format: "uuid" },
                      nama: { type: "string", example: "Budi Santoso" },
                      domisili: { type: "string", example: "Bandung" },
                      skill: { type: "array", items: { type: "string" }, example: ["First Aid", "Driving"] },
                      status: { type: "string", example: "pending" },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    "/api/misi/{mission_id}/apply": {
      post: {
        tags: ["Misi"],
        summary: "Apply to Mission (Legacy)",
        description: "Same as POST /api/apply. Provided for backwards compatibility.",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        parameters: [{ name: "mission_id", in: "path", required: true, schema: { type: "string", format: "uuid" } }],
        responses: {
          201: { description: "Applied" },
        },
      },
    },
    "/api/apply": {
      post: {
        tags: ["Apply"],
        summary: "Apply to a Mission",
        description: "Volunteers use this to apply for a mission. Includes a database-level lock (SELECT FOR UPDATE) to prevent over-quota applications during race conditions.",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                required: ["misi_id"],
                properties: {
                  misi_id: { type: "string", format: "uuid", example: "a1b2c3d4..." },
                },
              },
            },
          },
        },
        responses: {
          201: {
            description: "Berhasil apply",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    message: { type: "string" },
                    application_id: { type: "string", format: "uuid" },
                    status: { type: "string" },
                  },
                },
              },
            },
          },
          409: { description: "Misi sudah penuh, ditutup, atau sudah apply sebelumnya" },
        },
      },
    },
    "/api/apply/me": {
      get: {
        tags: ["Apply"],
        summary: "Get My Applications",
        description: "List all missions the authenticated volunteer has applied for.",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        responses: {
          200: {
            description: "Success",
            content: {
              "application/json": {
                schema: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      misi_id: { type: "string", format: "uuid" },
                      judul: { type: "string" },
                      status: { type: "string" },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    "/api/apply/{id}": {
      delete: {
        tags: ["Apply"],
        summary: "Cancel Application",
        description: "Volunteers can cancel their application if it's still in 'pending' status.",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }],
        responses: {
          200: { description: "Pendaftaran berhasil dibatalkan" },
          400: { description: "Sudah diproses, tidak dapat dibatalkan" },
        },
      },
    },
    "/api/apply/{id}/approve": {
      patch: {
        tags: ["Apply"],
        summary: "Approve Volunteer",
        description: "Institution approves a pending volunteer. Increments volunteers_applied count. If quota is met, mission status auto-advances to 'Full' (relawan_terkumpul).",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }],
        responses: {
          200: { description: "Relawan berhasil di-approve" },
          400: { description: "Kuota penuh atau status tidak valid" },
        },
      },
    },
    "/api/apply/{id}/reject": {
      patch: {
        tags: ["Apply"],
        summary: "Reject Volunteer",
        description: "Institution rejects a pending volunteer.",
        security: [{ cookieAuth: [] }, { bearerAuth: [] }],
        parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }],
        requestBody: {
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  reason: { type: "string", maxLength: 255, example: "Kapasitas kendaraan sudah penuh." },
                },
              },
            },
          },
        },
        responses: {
          200: { description: "Relawan berhasil ditolak" },
        },
      },
    },
    "/api/user/me": {
      get: {
        tags: ["User"],
        summary: "Get My Profile",
        description: "[PLACEHOLDER]",
        responses: { 200: { description: "OK" } },
      },
      put: {
        tags: ["User"],
        summary: "Update My Profile",
        description: "[PLACEHOLDER]",
        responses: { 200: { description: "OK" } },
      },
    },
    "/api/edukasi": {
      get: {
        tags: ["Edukasi"],
        summary: "Get All Educational Resources",
        description: "[PLACEHOLDER]",
        responses: { 200: { description: "OK" } },
      },
    },
    "/api/admin/users": {
      get: {
        tags: ["Admin"],
        summary: "Admin: Get All Users",
        description: "[PLACEHOLDER] Require super_admin role.",
        responses: { 200: { description: "OK" } },
      },
    },
  },
} as const satisfies OpenApiSpec
